Carcomponent
ilyris/jettby pull request #7
Opened 2022-05-17 02:44 UTC by bkandaris

Finished cards and carcomponent wrapper

2022-05-17 04:20 UTC, ilyris commented on components/FeaturedCars/CarCard/FeaturedWrapper/FeaturedCard.scss
> +  .featuredCard--wrapper {
&--wrapper

2022-05-17 04:20 UTC, ilyris commented on components/FeaturedCars/CarCard/FeaturedWrapper/FeaturedCard.scss
> +      .location--icon {
svg instead of .location--icon

2022-05-17 04:24 UTC, ilyris requested changes

2022-05-17 04:24 UTC, ilyris commented on components/FeaturedCars/CarCard/FeaturedWrapper/FeaturedWrapper.jsx
> +    <section className='featured--wrapper'>
FeaturedWrapper class

2022-05-17 04:24 UTC, ilyris commented on components/FeaturedCars/CarCard/FeaturedWrapper/FeaturedWrapper.jsx
> +        <div className='featured-card-wrapper'>
.FeaturedCard {
   > div // styles here
}

2022-05-17 04:24 UTC, ilyris commented on components/FeaturedCars/CarCard/FeaturedWrapper/FeaturedWrapper.jsx
> +          <Button variant='primary' className='featured--button'>
Just target button element in css

2022-05-17 04:24 UTC, ilyris commented on components/FeaturedCars/CarCard/FeaturedWrapper/FeaturedWrapper.scss
> +  .featured--title {
h3

2022-05-17 04:24 UTC, ilyris commented on components/FeaturedCars/CarCard/FeaturedWrapper/FeaturedWrapper.scss
> +  .featured--desc {
h5

2022-05-17 04:24 UTC, ilyris commented on components/FeaturedCars/CarCard/FeaturedWrapper/FeaturedWrapper.scss
> +  .featured-card-wrapper {
> div

2022-05-17 04:24 UTC, ilyris commented on components/FeaturedCars/CarCard/FeaturedWrapper/FeaturedWrapper.scss
> +  .featured--button {
button

2022-05-17 04:24 UTC, ilyris commented on components/Footer.jsx
> +        <div className='footer-wrapper'>
footer--wrapper

2022-05-18 01:51 UTC, bkandaris commented on components/FeaturedCars/CarCard/FeaturedWrapper/FeaturedCard.scss
> +  .featuredCard--wrapper {
Fixed

2022-05-18 01:52 UTC, bkandaris commented on components/FeaturedCars/CarCard/FeaturedWrapper/FeaturedCard.scss
> +      .location--icon {
Fixed

2022-05-18 01:53 UTC, bkandaris commented on components/FeaturedCars/CarCard/FeaturedWrapper/FeaturedWrapper.jsx
> +    <section className='featured--wrapper'>
Fixed

2022-05-18 01:55 UTC, bkandaris commented on components/FeaturedCars/CarCard/FeaturedWrapper/FeaturedWrapper.jsx
> +          <Button variant='primary' className='featured--button'>
fixed

2022-05-18 01:55 UTC, bkandaris commented on components/FeaturedCars/CarCard/FeaturedWrapper/FeaturedWrapper.scss
> +  .featured--title {
fixed

2022-05-18 01:56 UTC, bkandaris commented on components/FeaturedCars/CarCard/FeaturedWrapper/FeaturedWrapper.scss
> +  .featured--desc {
fixed

2022-05-18 02:23 UTC, bkandaris commented on components/FeaturedCars/CarCard/FeaturedWrapper/FeaturedWrapper.scss
> +  .featured--button {
fixed

2022-05-18 02:25 UTC, bkandaris commented on components/Footer.jsx
> +        <div className='footer-wrapper'>
Fixed

2022-05-18 02:29 UTC, bkandaris commented on components/FeaturedCars/CarCard/FeaturedWrapper/FeaturedWrapper.scss
> +  .featured-card-wrapper {
Fixed

2022-05-18 02:30 UTC, bkandaris commented on components/FeaturedCars/CarCard/FeaturedWrapper/FeaturedWrapper.jsx
> +        <div className='featured-card-wrapper'>
fixed

2022-05-19 03:55 UTC, closed without merging